import { getEbayAccessToken } from "@/lib/ebay-token";
import { getReportDateRange, type ReportPeriod } from "@/lib/report-periods";
import { fetchAllActiveListings } from "@/lib/ebay-price-update";
import { withEbayCache } from "@/lib/ebay-report-cache";

const METRICS = ["LISTING_IMPRESSION_TOTAL", "LISTING_VIEWS_TOTAL", "SALES_CONVERSION_RATE", "TRANSACTION"];

function toCompactDate(date: string): string {
  return date.replace(/-/g, "");
}

type EbayMetricRecord = {
  dimensionValues: { value: string }[];
  metricValues: { value: number }[];
};

export type ListingTrafficRecord = {
  itemId: string;
  impressions: number;
  views: number;
  salesConversionRate: number;
  // Sales/transactions attributed within the selected period — from eBay's own
  // per-listing traffic data, not our order DB (which has no eBay itemId to join on).
  soldInPeriod: number;
  title: string | null;
  imageUrl: string | null;
  // Total units sold on this listing since it was created/last relisted — an
  // eBay-maintained running total, NOT scoped to the selected period.
  totalQuantitySold: number | null;
};

export type ListingTrafficReport = {
  period: Exclude<ReportPeriod, "all">;
  range: { start: string; end: string };
  listings: ListingTrafficRecord[];
};

/**
 * Per-listing eBay traffic (impressions/views/etc), sorted by impressions descending.
 * Shared by the eBay Traffic Report → Listings tab and the Daily Report's eBay card —
 * same cache key ("traffic_listings" + period), so a report generated by one is reused
 * by the other instead of hitting eBay's Analytics API twice for the same window.
 * `stale`/`fetchedAt` (from withEbayCache) tell the caller whether this is a live
 * result or a fallback from the last successful fetch.
 */
export async function fetchListingTrafficReport(
  period: Exclude<ReportPeriod, "all">
): Promise<{ report: ListingTrafficReport; stale: boolean; fetchedAt: string | null }> {
  const { data, stale, fetchedAt } = await withEbayCache("traffic_listings", { period }, async () => {
    const { start, end } = getReportDateRange(period);
    const token = await getEbayAccessToken();

    const filter = `marketplace_ids:{EBAY_US},date_range:[${toCompactDate(start)}..${toCompactDate(end)}]`;
    const url = `https://api.ebay.com/sell/analytics/v1/traffic_report?filter=${encodeURIComponent(filter)}&dimension=LISTING&metric=${METRICS.join(",")}&sort=-LISTING_IMPRESSION_TOTAL`;

    const res = await fetch(url, {
      headers: { Authorization: `Bearer ${token}`, "X-EBAY-C-MARKETPLACE-ID": "EBAY_US" },
    });
    const body = await res.json();

    if (!res.ok) {
      const message = body?.errors?.[0]?.message || `eBay respondeu ${res.status}`;
      throw new Error(message);
    }

    const metricKeys: string[] = (body.header?.metrics ?? []).map((m: { key: string }) => m.key);
    const records = (body.records ?? []) as EbayMetricRecord[];

    const parsed = records.map((r) => {
      const itemId = r.dimensionValues?.[0]?.value ?? "";
      const values: Record<string, number> = {};
      (r.metricValues ?? []).forEach((mv, i) => { values[metricKeys[i]] = mv.value; });
      return {
        itemId,
        impressions: values.LISTING_IMPRESSION_TOTAL ?? 0,
        views: values.LISTING_VIEWS_TOTAL ?? 0,
        salesConversionRate: values.SALES_CONVERSION_RATE ?? 0,
        soldInPeriod: values.TRANSACTION ?? 0,
      };
    });

    // Enrich with title/image/lifetime QuantitySold from the seller's active listing
    // catalog — best-effort, a lookup failure shouldn't hide the traffic numbers themselves.
    let catalogById = new Map<string, { title: string; imageUrl?: string; quantitySold?: number }>();
    try {
      const listings = await fetchAllActiveListings();
      catalogById = new Map(listings.map((l) => [l.itemId, { title: l.title, imageUrl: l.imageUrl, quantitySold: l.quantitySold }]));
    } catch {
      // ignore — listings render with itemId only
    }

    return {
      period,
      range: { start, end },
      listings: parsed.map((r) => {
        const catalog = catalogById.get(r.itemId);
        return {
          ...r,
          title: catalog?.title ?? null,
          imageUrl: catalog?.imageUrl ?? null,
          totalQuantitySold: catalog?.quantitySold ?? null,
        };
      }),
    };
  });

  return { report: data, stale, fetchedAt };
}
