SET search_path TO vertex, extensions;

-- Stores one row per day generated by /api/cron/daily-report — the whole aggregated
-- payload (sales, site traffic, catalog counts per channel, eBay traffic, insights) as a
-- single jsonb blob, since the shape is expected to keep evolving and the admin page
-- always reads it as a whole rather than querying individual fields.
CREATE TABLE IF NOT EXISTS vertex.daily_reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  report_date DATE NOT NULL UNIQUE,
  data JSONB NOT NULL,
  insights JSONB NOT NULL,
  insights_source TEXT NOT NULL DEFAULT 'rules',
  generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE vertex.daily_reports ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can view daily reports"
  ON vertex.daily_reports
  FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Admin and operador can manage daily reports"
  ON vertex.daily_reports
  FOR ALL
  TO authenticated
  USING (get_current_user_role() = ANY (ARRAY['admin'::app_role, 'operador'::app_role]))
  WITH CHECK (get_current_user_role() = ANY (ARRAY['admin'::app_role, 'operador'::app_role]));

INSERT INTO vertex.push_notifications (trigger_key, enabled, title, message, tags) VALUES
('daily_report', true, '📊 Resumo diário disponível', 'Vendas: {revenue} | Sessões do site: {sessions}
Toque para ver o relatório completo.', 'bar_chart')
ON CONFLICT (trigger_key) DO NOTHING;
